# load model

In [1]:
import tensorflow as tf
import sys
sys.path.append("C://Users/Admin/Desktop/000-data_science/sem2-project_1/treepedia_dl_public-master")

import model_lib as treepedia_dl
import matplotlib.pyplot as plt
import cv2
import numpy as np

In [5]:
model = tf.keras.models.load_model( "C://Users/Admin/Desktop/000-data_science/sem2-project_1/treepedia_dl_public-master/weights_test.hdf5")

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 1000)              25636712  
                                                                 
 dense_1 (Dense)             (None, 256)               256256    
                                                                 
 dense_2 (Dense)             (None, 256)               65792     
                                                                 
 dense_3 (Dense)             (None, 256)               65792     
                                                                 
 dense_4 (Dense)             (None, 256)               65792     
                                                                 
 dense_5 (Dense)             (None, 1)                 257       
                                                                 
Total params: 26,090,601
Trainable params: 26,037,481
No

# change labelled png data into two channel label jpg

In [18]:
# load the png file paths for test data
fix_png = "C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/fix_png.txt"
with open(fix_png, 'r') as training:
        content = training.readlines()
        png_paths = []

        for lines in content: 
                lines = lines.replace('\n', '')
                png_paths.append(lines)
        

In [19]:
png_paths

['C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.45792-103.769025-0.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.45792-103.769025-60.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.45792-103.769025-120.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.45792-103.769025-180.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.45792-103.769025-240.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.45792-103.769025-300.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.46517-103.7589044-0.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.46517-103.7589044-60.png',
 'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/1.46517-103.7589

In [27]:
import os

test_datas = []
for file_name in os.listdir("images/mask/test_data"):
    if file_name.endswith('.jpg'):
         # Split the file name into its components using the '-' separator
        file_components = file_name.split('-')
        # Extract the latitude, longitude, and heading information from the file name
        lat = (file_components[0])
        lng = (file_components[1])
        heading = int(file_components[2].split('.')[0])
        # Add the information to the dataframe as a new row
        test_datas.append([lat, lng, heading])

test_datas

[['1.4574946', '103.7690224', 0],
 ['1.4574946', '103.7690224', 120],
 ['1.4574946', '103.7690224', 180],
 ['1.4574946', '103.7690224', 240],
 ['1.4574946', '103.7690224', 300],
 ['1.4574946', '103.7690224', 60],
 ['1.4576324', '103.7689637', 0],
 ['1.4576324', '103.7689637', 120],
 ['1.4576324', '103.7689637', 180],
 ['1.4576324', '103.7689637', 240],
 ['1.4576324', '103.7689637', 300],
 ['1.4576324', '103.7689637', 60],
 ['1.4578067', '103.7675917', 0],
 ['1.4578067', '103.7675917', 120],
 ['1.4578067', '103.7675917', 180],
 ['1.4578067', '103.7675917', 240],
 ['1.4578067', '103.7675917', 300],
 ['1.4578067', '103.7675917', 60],
 ['1.45792', '103.769025', 300],
 ['1.4581955', '103.7692668', 0],
 ['1.4581955', '103.7692668', 120],
 ['1.4581955', '103.7692668', 180],
 ['1.4581955', '103.7692668', 240],
 ['1.4581955', '103.7692668', 300],
 ['1.4581955', '103.7692668', 60],
 ['1.4583986', '103.7694707', 0],
 ['1.4583986', '103.7694707', 120],
 ['1.4583986', '103.7694707', 180],
 ['1.4583

In [30]:
for test_data in test_datas:
    lat, lng, heading = test_data[0],test_data[1], test_data[2]
    test_lbl = f'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/testlabel_png/{lat}-{lng}-{heading}.png'
    img = Image.open(test_lbl)
    img = img.convert('L')
    # image = Image.fromarray(imgg)
    
    img.save(f'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/fixed_label/{lat}-{lng}-{heading}.jpg') 
    #f.write(image)

# f.close()

In [23]:
from PIL import Image

# convert the png files to 2 channels jpg
for line, test_label in zip(range(len(png_paths)), test_lbl):
    lat, lng, heading = test_label[0],test_label[1], test_label[2]
    img = Image.open(png_paths[line])
    img = img.convert('L')
    # image = Image.fromarray(imgg)
    
    img.save(f'C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/fixed_label/{lat}-{lng}-{heading}.jpg') 
    #f.write(image)

# f.close()

In [2]:
# test if they have been successfully transformed
plt.imread("C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/fixed_images/fixed_0.jpg").shape

(640, 640)

# load test data for preparation 

In [5]:
def load_and_resize(image_loc):
    '''
    load image and ground truth label data with txt file consisting image data file paths
    '''
    test_data = []
    test_gt = []
    with open(image_loc, 'r') as training:
        content = training.readlines()
    for line in content:
        paths = line.split()
        if len(paths) == 2:
            test_data.append(paths[0])
            test_gt.append(paths[1].replace("\n", ""))
        if len(paths) == 3:
            test_data.append(paths[0] + " "+paths[1])
            test_gt.append(paths[2].replace("\n", ""))
    imgdata = []
    for path1 in test_data:
        imgdata.append((Image.open(path1)).resize(current_model[0:2]))
    labeldata = []
    for path in test_gt:
        labeldata.append(np.sum(np.asarray((Image.open(path)).resize(current_model[0:2])) != 0)*1.0 /
                         (current_model[0]*current_model[1]))
    imgdata_array = np.zeros(
        [len(imgdata), current_model[0], current_model[1], current_model[2]])
    labeldata_array = np.zeros([len(imgdata), 1])
    for i in range(len(imgdata)):
        imgdata_array[i, :, :, :] = imgdata[i]
        labeldata_array[i, :] = labeldata[i]
    del (imgdata, labeldata)
    return (imgdata_array, labeldata_array)

In [31]:
imgdata_array, labeldata_array = treepedia_dl.load_and_resize(
    "C://Users/Admin/Desktop/000-data_science/sem2-project_1/images/mask/jpg_test_data.txt")

In [35]:
# image array
imgdata_array.shape
np.save('test_data_array.npy', imgdata_array)

In [33]:
# array of GVI ground truth
labeldata_array
np.save('true_GVI_test.npy', labeldata_array)

In [34]:
np.load('true_GVI_test.npy')

array([[0.60094467],
       [0.3126993 ],
       [0.50051818],
       [0.3052854 ],
       [0.64861687],
       [0.58444276],
       [0.50061783],
       [0.45487883],
       [0.3458227 ],
       [0.59105947],
       [0.78125   ],
       [0.67480469],
       [0.00486288],
       [0.        ],
       [0.02188297],
       [0.06437341],
       [0.        ],
       [0.01937181],
       [0.36742666],
       [0.06407446],
       [0.29342714],
       [0.48128587],
       [0.17364876],
       [0.05919165],
       [0.064772  ],
       [0.83442283],
       [0.6038345 ],
       [0.47981107],
       [0.57226562],
       [0.70304528],
       [0.51311384],
       [0.        ],
       [0.24358259],
       [0.05291374],
       [0.10672433],
       [0.        ],
       [0.13757573],
       [0.84703842],
       [0.45762915],
       [0.        ]])

# test DCNN prediction accuracy

In [16]:
# GVI predicted with DCNN model
DCNN_pred = treepedia_dl.eval_batch(model, imgdata_array, 100, 1)
DCNN_pred

1/1 [==============================] - 3s 3s/step


array([[0.3106264 ],
       [0.5160212 ],
       [0.18007785],
       [0.09406929],
       [0.11547126],
       [0.2521316 ],
       [0.13138202],
       [0.04073031],
       [0.05839574],
       [0.04726631],
       [0.6342129 ],
       [0.29890087],
       [0.22126643],
       [0.22700313],
       [0.17545329],
       [0.31126994],
       [0.23843314],
       [0.35760412],
       [0.23956876],
       [0.3875342 ],
       [0.19396795],
       [0.18305703],
       [0.31971508],
       [0.3970952 ],
       [0.05750674],
       [0.08364543],
       [0.0743855 ],
       [0.09982818],
       [0.13972105],
       [0.07007068],
       [0.09495103],
       [0.10827843],
       [0.21562845],
       [0.2884954 ],
       [0.11649828],
       [0.1218613 ],
       [0.49834064],
       [0.2311715 ],
       [0.25066155],
       [0.19634311],
       [0.40027127],
       [0.59893364],
       [0.04003099],
       [0.07372795],
       [0.16780147]], dtype=float32)

In [19]:
# compute difference between prediction and true GVI
diff = np.zeros([len(DCNN_pred), 1])
for i in range(len(DCNN_pred)):
    diff[i] = DCNN_pred[i]-labeldata_array[i]

# evaluate accuracy of model
print("Average Absolute GVI error is: %f" % np.mean(np.abs(diff)))
percentile_result = np.percentile(diff, [5, 95])
print("5-95 percentile of Absolute GVI error is (%f, %f)" %
      (percentile_result[0], percentile_result[1]))
print("Correlation of predicted and true GVI is: %f" %
      np.corrcoef(DCNN_pred.T, labeldata_array.T)[0, 1])

Average Absolute GVI error is: 0.146651
5-95 percentile of Absolute GVI error is (-0.356586, 0.073523)
Correlation of predicted and true GVI is: 0.892504


# test unsupervised classification

In [22]:
def unsupervised_GVI_pred(images):
    red = images[:, :, :, 0]
    green = images[:, :, :, 1]
    blue = images[:, :, :, 2]

    diff_1 = green - red
    diff_2 = green - blue

    diff_1[diff_1 < 0] = 0
    diff_2[diff_2 < 0] = 0

    Diff = diff_1 * diff_2

    unsupervised_GVI_pred =[]

    for i in range(len(Diff)):
        pred = (np.sum(Diff[i] != 0) ) / (224*224)
        unsupervised_GVI_pred.append(pred)

    unsupervised_GVI_pred = np.array(unsupervised_GVI_pred)

    return unsupervised_GVI_pred



In [24]:
unsupervised_GVI_pred = unsupervised_GVI_pred(imgdata_array)
unsupervised_GVI_pred

array([0.34339126, 0.60947465, 0.4091199 , 0.35598693, 0.18831712,
       0.33527982, 0.1419603 , 0.03824538, 0.06752232, 0.16675303,
       0.67332988, 0.3446867 , 0.53730867, 0.5966199 , 0.39365434,
       0.47341358, 0.4171317 , 0.6310786 , 0.5840043 , 0.63408801,
       0.46314971, 0.38113839, 0.60479114, 0.73307956, 0.00984534,
       0.04615753, 0.0180963 , 0.05604273, 0.0609654 , 0.01638233,
       0.08141342, 0.19391741, 0.23447465, 0.30897242, 0.25751355,
       0.08689413, 0.71906888, 0.57820472, 0.58645568, 0.66344467,
       0.55245536, 0.68755979, 0.48883929, 0.23102679, 0.29972497])

In [25]:
# compute difference between prediction and true GVI
diff = np.zeros([len(unsupervised_GVI_pred), 1])
for i in range(len(unsupervised_GVI_pred)):
    diff[i] = unsupervised_GVI_pred[i]-labeldata_array[i]

# evaluate accuracy of model
print("Average Absolute GVI error is: %f" % np.mean(np.abs(diff)))
percentile_result = np.percentile(diff, [5, 95])
print("5-95 percentile of Absolute GVI error is (%f, %f)" %
      (percentile_result[0], percentile_result[1]))
print("Correlation of predicted and true GVI is: %f" %
      np.corrcoef(unsupervised_GVI_pred.T, labeldata_array.T)[0, 1])

Average Absolute GVI error is: 0.073144
5-95 percentile of Absolute GVI error is (-0.114872, 0.182529)
Correlation of predicted and true GVI is: 0.909168
